// ecosystem.config.cjs - Generated by webdev:spinup
// Port: 4000 (from port registry)
// PM2 Name: dev-server-dewaterquote
module.exports = {
  apps: [{
    name: 'dev-server-dewaterquote',
    script: 'vercel',
    args: 'dev --port 4000',
    cwd: __dirname,
    autorestart: true,
    watch: false,
    max_restarts: 50,
    restart_delay: 2000,
    env: {
      NODE_ENV: 'development'
    }
  }]
};
